/**
 * Generates placeholder answers using Lorem Ipsum
 * This function should be replaced with real GPT extraction later
 */
import type { AnswerBlock } from "./types";

export function generatePlaceholderAnswers(
  questions: string[],
  englishTranscript?: string
): AnswerBlock[] {
  const answers = questions.map((question, index) => {
    // Generate Lorem Ipsum answer (2 sentences)
    const answer = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`;

    // Extract a quote from English transcript if available
    let quotes: Array<{ quote: string; note?: string }> | undefined;
    if (englishTranscript) {
      const sentences = englishTranscript.split(/[.!?]+/).filter((s) => s.trim().length > 20);
      if (sentences.length > 0) {
        const randomSentence = sentences[index % sentences.length]?.trim();
        if (randomSentence) {
          quotes = [{
            quote: randomSentence.substring(0, 150), // Limit quote length
            note: "Sample quote from transcript",
          }];
        }
      }
    }

    return {
      question,
      answer,
      quotes: quotes || [{ quote: `Sample quote from transcript ${index + 1}.` }],
      reasoning: "Generated by AI placeholder.",
    };
  });

  return answers;
}
